language: python
sudo: required

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - curl
      - wget
      
install:
- sudo bash -x scripts/provision.sh
- sudo curl -sL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- sudo unzip -d /usr/local/bin /tmp/terraform.zip
script:
- curl -sL http://127.0.0.1:80
- curl -sL http://127.0.0.1:80 | grep 'Visit Bulgaria.'
- cd ops
- terraform fmt
- terraform init
